// Generated by CoffeeScript 1.4.0
(function() {
  var $drop_file, div, drop_file_node, noop_func, pdf_parse;

  pdf_parse = require("./app/parse.js").PdfParse;

  $drop_file = $("#drop-file");

  drop_file_node = $drop_file[0];

  div = "<div class='foo'></div>";

  noop_func = function(e) {
    e.stopPropagation();
    return e.preventDefault();
  };

  drop_file_node.addEventListener("dragenter", noop_func, false);

  drop_file_node.addEventListener("dragexit", noop_func, false);

  drop_file_node.addEventListener("dragover", noop_func, false);

  drop_file_node.addEventListener("drop", (function(ev) {
    ev.stopPropagation();
    ev.preventDefault();
    return _(ev.dataTransfer.files).each(function(v) {
      return pdf_parse(v.path.replace(/\\/g, "\\\\"), function(data) {
        return console.log(data);
      });
    });
  }), false);

}).call(this);
